import { useState } from 'react';
import { ProductCard } from './ProductCard';
import { GiftCard } from './GiftCard';
import { MoneyTransfer } from './MoneyTransfer';
import { Button } from '@/components/ui/button';
import { Filter } from 'lucide-react';

interface ProductGridProps {
  user: any;
}

// Comprehensive card database with 67 premium cards
const sampleProducts = [
  // Premium Tier Cards (80% success rate - £13)
  {
    id: '1',
    bin: '4532 15** **** ****',
    expiryMonth: '12',
    expiryYear: '26',
    cvv: '***',
    bank: 'Chase Bank',
    country: 'United States',
    balance: '$2,500',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '2',
    bin: '4000 00** **** ****',
    expiryMonth: '03',
    expiryYear: '26',
    cvv: '***',
    bank: 'Barclays',
    country: 'United Kingdom',
    balance: '£3,200',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '3',
    bin: '4111 11** **** ****',
    expiryMonth: '08',
    expiryYear: '27',
    cvv: '***',
    bank: 'Deutsche Bank',
    country: 'Germany',
    balance: '€2,800',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '4',
    bin: '4532 88** **** ****',
    expiryMonth: '05',
    expiryYear: '28',
    cvv: '***',
    bank: 'JP Morgan',
    country: 'United States',
    balance: '$4,100',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '5',
    bin: '4000 12** **** ****',
    expiryMonth: '11',
    expiryYear: '26',
    cvv: '***',
    bank: 'HSBC',
    country: 'United Kingdom',
    balance: '£2,750',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '6',
    bin: '4532 44** **** ****',
    expiryMonth: '07',
    expiryYear: '27',
    cvv: '***',
    bank: 'Bank of America',
    country: 'United States',
    balance: '$3,600',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '7',
    bin: '4111 22** **** ****',
    expiryMonth: '09',
    expiryYear: '25',
    cvv: '***',
    bank: 'Credit Suisse',
    country: 'Switzerland',
    balance: 'CHF 3,100',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '8',
    bin: '4532 77** **** ****',
    expiryMonth: '04',
    expiryYear: '27',
    cvv: '***',
    bank: 'Wells Fargo',
    country: 'United States',
    balance: '$2,900',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '9',
    bin: '4000 33** **** ****',
    expiryMonth: '12',
    expiryYear: '25',
    cvv: '***',
    bank: 'Lloyds Banking',
    country: 'United Kingdom',
    balance: '£3,400',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '10',
    bin: '4532 99** **** ****',
    expiryMonth: '06',
    expiryYear: '28',
    cvv: '***',
    bank: 'Citibank',
    country: 'United States',
    balance: '$5,200',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '11',
    bin: '4111 55** **** ****',
    expiryMonth: '02',
    expiryYear: '27',
    cvv: '***',
    bank: 'BNP Paribas',
    country: 'France',
    balance: '€3,300',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '12',
    bin: '4000 66** **** ****',
    expiryMonth: '10',
    expiryYear: '26',
    cvv: '***',
    bank: 'Royal Bank',
    country: 'Canada',
    balance: 'CAD $3,800',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '13',
    bin: '4532 11** **** ****',
    expiryMonth: '01',
    expiryYear: '28',
    cvv: '***',
    bank: 'Goldman Sachs',
    country: 'United States',
    balance: '$4,700',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '14',
    bin: '4111 88** **** ****',
    expiryMonth: '08',
    expiryYear: '26',
    cvv: '***',
    bank: 'ING Bank',
    country: 'Netherlands',
    balance: '€2,600',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '15',
    bin: '4000 99** **** ****',
    expiryMonth: '03',
    expiryYear: '27',
    cvv: '***',
    bank: 'Santander',
    country: 'Spain',
    balance: '€3,100',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '16',
    bin: '4532 22** **** ****',
    expiryMonth: '05',
    expiryYear: '26',
    cvv: '***',
    bank: 'Morgan Stanley',
    country: 'United States',
    balance: '$3,900',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '17',
    bin: '4111 77** **** ****',
    expiryMonth: '09',
    expiryYear: '27',
    cvv: '***',
    bank: 'UBS',
    country: 'Switzerland',
    balance: 'CHF 4,200',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '18',
    bin: '4000 44** **** ****',
    expiryMonth: '07',
    expiryYear: '25',
    cvv: '***',
    bank: 'Standard Chartered',
    country: 'United Kingdom',
    balance: '£2,850',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '19',
    bin: '4532 66** **** ****',
    expiryMonth: '11',
    expiryYear: '27',
    cvv: '***',
    bank: 'TD Bank',
    country: 'Canada',
    balance: 'CAD $3,500',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '20',
    bin: '4111 33** **** ****',
    expiryMonth: '04',
    expiryYear: '28',
    cvv: '***',
    bank: 'BBVA',
    country: 'Spain',
    balance: '€2,750',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '21',
    bin: '4000 77** **** ****',
    expiryMonth: '12',
    expiryYear: '26',
    cvv: '***',
    bank: 'NatWest',
    country: 'United Kingdom',
    balance: '£3,650',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },
  {
    id: '22',
    bin: '4532 33** **** ****',
    expiryMonth: '06',
    expiryYear: '27',
    cvv: '***',
    bank: 'PNC Bank',
    country: 'United States',
    balance: '$3,200',
    price: 13,
    successRate: 80,
    tier: 'premium' as const,
  },

  // Standard Tier Cards (50% success rate - £10)
  {
    id: '23',
    bin: '5555 44** **** ****',
    expiryMonth: '09',
    expiryYear: '25',
    cvv: '***',
    bank: 'Bank of America',
    country: 'United States',
    balance: '$1,800',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '24',
    bin: '5105 10** **** ****',
    expiryMonth: '11',
    expiryYear: '25',
    cvv: '***',
    bank: 'HSBC',
    country: 'United Kingdom',
    balance: '£1,650',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '25',
    bin: '5555 77** **** ****',
    expiryMonth: '03',
    expiryYear: '26',
    cvv: '***',
    bank: 'Capital One',
    country: 'United States',
    balance: '$2,100',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '26',
    bin: '5105 33** **** ****',
    expiryMonth: '07',
    expiryYear: '26',
    cvv: '***',
    bank: 'Danske Bank',
    country: 'Denmark',
    balance: 'DKK 12,500',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '27',
    bin: '5555 22** **** ****',
    expiryMonth: '05',
    expiryYear: '27',
    cvv: '***',
    bank: 'U.S. Bank',
    country: 'United States',
    balance: '$1,950',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '28',
    bin: '5105 66** **** ****',
    expiryMonth: '12',
    expiryYear: '25',
    cvv: '***',
    bank: 'Halifax',
    country: 'United Kingdom',
    balance: '£1,750',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '29',
    bin: '5555 88** **** ****',
    expiryMonth: '08',
    expiryYear: '26',
    cvv: '***',
    bank: 'Regions Bank',
    country: 'United States',
    balance: '$1,600',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '30',
    bin: '5105 99** **** ****',
    expiryMonth: '04',
    expiryYear: '27',
    cvv: '***',
    bank: 'Commerzbank',
    country: 'Germany',
    balance: '€1,850',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '31',
    bin: '5555 11** **** ****',
    expiryMonth: '10',
    expiryYear: '25',
    cvv: '***',
    bank: 'Truist Bank',
    country: 'United States',
    balance: '$2,200',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '32',
    bin: '5105 44** **** ****',
    expiryMonth: '02',
    expiryYear: '27',
    cvv: '***',
    bank: 'Nationwide',
    country: 'United Kingdom',
    balance: '£1,900',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '33',
    bin: '5555 55** **** ****',
    expiryMonth: '06',
    expiryYear: '26',
    cvv: '***',
    bank: 'Fifth Third Bank',
    country: 'United States',
    balance: '$1,750',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '34',
    bin: '5105 77** **** ****',
    expiryMonth: '09',
    expiryYear: '26',
    cvv: '***',
    bank: 'Rabobank',
    country: 'Netherlands',
    balance: '€1,950',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '35',
    bin: '5555 99** **** ****',
    expiryMonth: '01',
    expiryYear: '28',
    cvv: '***',
    bank: 'KeyBank',
    country: 'United States',
    balance: '$1,850',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '36',
    bin: '5105 22** **** ****',
    expiryMonth: '11',
    expiryYear: '26',
    cvv: '***',
    bank: 'TSB Bank',
    country: 'United Kingdom',
    balance: '£1,650',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '37',
    bin: '5555 66** **** ****',
    expiryMonth: '03',
    expiryYear: '27',
    cvv: '***',
    bank: 'Huntington Bank',
    country: 'United States',
    balance: '$2,050',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '38',
    bin: '5105 88** **** ****',
    expiryMonth: '07',
    expiryYear: '25',
    cvv: '***',
    bank: 'UniCredit',
    country: 'Italy',
    balance: '€1,750',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '39',
    bin: '5555 33** **** ****',
    expiryMonth: '05',
    expiryYear: '26',
    cvv: '***',
    bank: 'M&T Bank',
    country: 'United States',
    balance: '$1,900',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '40',
    bin: '5105 11** **** ****',
    expiryMonth: '12',
    expiryYear: '27',
    cvv: '***',
    bank: 'First Direct',
    country: 'United Kingdom',
    balance: '£2,100',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '41',
    bin: '5555 00** **** ****',
    expiryMonth: '08',
    expiryYear: '27',
    cvv: '***',
    bank: 'Ally Bank',
    country: 'United States',
    balance: '$1,800',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },
  {
    id: '42',
    bin: '5105 55** **** ****',
    expiryMonth: '04',
    expiryYear: '26',
    cvv: '***',
    bank: 'ABN AMRO',
    country: 'Netherlands',
    balance: '€1,650',
    price: 10,
    successRate: 50,
    tier: 'standard' as const,
  },

  // Basic Tier Cards (30% success rate - £7)
  {
    id: '43',
    bin: '4111 11** **** ****',
    expiryMonth: '06',
    expiryYear: '27',
    cvv: '***',
    bank: 'Wells Fargo',
    country: 'United States',
    balance: '$950',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '44',
    bin: '3782 82** **** ****',
    expiryMonth: '08',
    expiryYear: '27',
    cvv: '***',
    bank: 'American Express',
    country: 'Canada',
    balance: 'CAD $2,100',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '45',
    bin: '4111 44** **** ****',
    expiryMonth: '02',
    expiryYear: '26',
    cvv: '***',
    bank: 'Discover Bank',
    country: 'United States',
    balance: '$1,200',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '46',
    bin: '4111 77** **** ****',
    expiryMonth: '10',
    expiryYear: '25',
    cvv: '***',
    bank: 'Metro Bank',
    country: 'United Kingdom',
    balance: '£850',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '47',
    bin: '4111 99** **** ****',
    expiryMonth: '05',
    expiryYear: '26',
    cvv: '***',
    bank: 'SunTrust Bank',
    country: 'United States',
    balance: '$1,100',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '48',
    bin: '4111 22** **** ****',
    expiryMonth: '09',
    expiryYear: '26',
    cvv: '***',
    bank: 'Monzo',
    country: 'United Kingdom',
    balance: '£950',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '49',
    bin: '4111 55** **** ****',
    expiryMonth: '07',
    expiryYear: '25',
    cvv: '***',
    bank: 'BB&T',
    country: 'United States',
    balance: '$800',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '50',
    bin: '4111 88** **** ****',
    expiryMonth: '11',
    expiryYear: '26',
    cvv: '***',
    bank: 'Starling Bank',
    country: 'United Kingdom',
    balance: '£1,050',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '51',
    bin: '4111 00** **** ****',
    expiryMonth: '03',
    expiryYear: '27',
    cvv: '***',
    bank: 'Citizens Bank',
    country: 'United States',
    balance: '$900',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '52',
    bin: '4111 33** **** ****',
    expiryMonth: '12',
    expiryYear: '25',
    cvv: '***',
    bank: 'Revolut',
    country: 'United Kingdom',
    balance: '£750',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '53',
    bin: '4111 66** **** ****',
    expiryMonth: '04',
    expiryYear: '26',
    cvv: '***',
    bank: 'Comerica Bank',
    country: 'United States',
    balance: '$1,150',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '54',
    bin: '3782 99** **** ****',
    expiryMonth: '08',
    expiryYear: '26',
    cvv: '***',
    bank: 'American Express',
    country: 'United States',
    balance: '$1,300',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '55',
    bin: '4111 12** **** ****',
    expiryMonth: '01',
    expiryYear: '27',
    cvv: '***',
    bank: 'Zions Bank',
    country: 'United States',
    balance: '$950',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '56',
    bin: '4111 45** **** ****',
    expiryMonth: '06',
    expiryYear: '25',
    cvv: '***',
    bank: 'Co-operative Bank',
    country: 'United Kingdom',
    balance: '£800',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '57',
    bin: '4111 78** **** ****',
    expiryMonth: '09',
    expiryYear: '27',
    cvv: '***',
    bank: 'First National Bank',
    country: 'United States',
    balance: '$1,050',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '58',
    bin: '4111 90** **** ****',
    expiryMonth: '11',
    expiryYear: '25',
    cvv: '***',
    bank: 'Virgin Money',
    country: 'United Kingdom',
    balance: '£900',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '59',
    bin: '4111 23** **** ****',
    expiryMonth: '02',
    expiryYear: '27',
    cvv: '***',
    bank: 'Associated Bank',
    country: 'United States',
    balance: '$850',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '60',
    bin: '4111 56** **** ****',
    expiryMonth: '05',
    expiryYear: '28',
    cvv: '***',
    bank: 'Tesco Bank',
    country: 'United Kingdom',
    balance: '£1,100',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '61',
    bin: '4111 89** **** ****',
    expiryMonth: '07',
    expiryYear: '26',
    cvv: '***',
    bank: 'Frost Bank',
    country: 'United States',
    balance: '$950',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '62',
    bin: '3782 11** **** ****',
    expiryMonth: '10',
    expiryYear: '26',
    cvv: '***',
    bank: 'American Express',
    country: 'United Kingdom',
    balance: '£1,200',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '63',
    bin: '4111 34** **** ****',
    expiryMonth: '03',
    expiryYear: '26',
    cvv: '***',
    bank: 'Bank of the West',
    country: 'United States',
    balance: '$750',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '64',
    bin: '4111 67** **** ****',
    expiryMonth: '12',
    expiryYear: '26',
    cvv: '***',
    bank: 'Santander UK',
    country: 'United Kingdom',
    balance: '£850',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '65',
    bin: '4111 91** **** ****',
    expiryMonth: '08',
    expiryYear: '25',
    cvv: '***',
    bank: 'First Citizens Bank',
    country: 'United States',
    balance: '$1,000',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '66',
    bin: '4111 24** **** ****',
    expiryMonth: '04',
    expiryYear: '27',
    cvv: '***',
    bank: 'CYBG',
    country: 'United Kingdom',
    balance: '£950',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
  {
    id: '67',
    bin: '4111 57** **** ****',
    expiryMonth: '01',
    expiryYear: '28',
    cvv: '***',
    bank: 'Eastern Bank',
    country: 'United States',
    balance: '$900',
    price: 7,
    successRate: 30,
    tier: 'basic' as const,
  },
];

// Gift Cards
const giftCardProducts = [
  // $500 Gift Cards for $40
  { id: 'gc1', brand: 'Amazon', value: 500, price: 40, tier: 'giftcard' as const },
  { id: 'gc2', brand: 'Target', value: 500, price: 40, tier: 'giftcard' as const },
  { id: 'gc3', brand: 'eBay', value: 500, price: 40, tier: 'giftcard' as const },
  // $1000 Gift Cards for $60
  { id: 'gc4', brand: 'Amazon', value: 1000, price: 60, tier: 'giftcard' as const },
  { id: 'gc5', brand: 'Target', value: 1000, price: 60, tier: 'giftcard' as const },
  { id: 'gc6', brand: 'eBay', value: 1000, price: 60, tier: 'giftcard' as const },
  // $1500 Gift Cards for $79.99
  { id: 'gc7', brand: 'Amazon', value: 1500, price: 79.99, tier: 'giftcard' as const },
  { id: 'gc8', brand: 'Target', value: 1500, price: 79.99, tier: 'giftcard' as const },
  { id: 'gc9', brand: 'eBay', value: 1500, price: 79.99, tier: 'giftcard' as const },
  // $2000 Gift Cards for $90
  { id: 'gc10', brand: 'Amazon', value: 2000, price: 90, tier: 'giftcard' as const },
  { id: 'gc11', brand: 'Target', value: 2000, price: 90, tier: 'giftcard' as const },
  { id: 'gc12', brand: 'eBay', value: 2000, price: 90, tier: 'giftcard' as const },
];

// Money Transfers
const moneyTransferProducts = [
  // $500 transfers for $70
  { id: 'mt1', provider: 'PayPal', value: 500, price: 70, tier: 'transfer' as const },
  { id: 'mt2', provider: 'Western Union', value: 500, price: 70, tier: 'transfer' as const },
  { id: 'mt3', provider: 'MoneyGram', value: 500, price: 70, tier: 'transfer' as const },
  { id: 'mt4', provider: 'Cash App', value: 500, price: 70, tier: 'transfer' as const },
  // $2500 transfers for $120
  { id: 'mt5', provider: 'PayPal', value: 2500, price: 120, tier: 'transfer' as const },
  { id: 'mt6', provider: 'Western Union', value: 2500, price: 120, tier: 'transfer' as const },
  { id: 'mt7', provider: 'MoneyGram', value: 2500, price: 120, tier: 'transfer' as const },
  { id: 'mt8', provider: 'Cash App', value: 2500, price: 120, tier: 'transfer' as const },
];

export function ProductGrid({ user }: ProductGridProps) {
  const [filter, setFilter] = useState<'all' | 'premium' | 'standard' | 'basic' | 'giftcard' | 'transfer'>('all');

  const filteredProducts = filter === 'all' 
    ? sampleProducts 
    : filter === 'giftcard' || filter === 'transfer'
    ? []
    : sampleProducts.filter(product => product.tier === filter);

  const filteredGiftCards = filter === 'all' || filter === 'giftcard' 
    ? giftCardProducts 
    : [];

  const filteredTransfers = filter === 'all' || filter === 'transfer'
    ? moneyTransferProducts
    : [];

  if (!user) {
    return (
      <section className="py-20">
        <div className="container mx-auto px-4 text-center">
          <div className="bg-card border border-border rounded-2xl p-12 max-w-md mx-auto">
            <div className="w-16 h-16 bg-primary/20 rounded-full flex items-center justify-center mx-auto mb-6">
              <Filter className="w-8 h-8 text-primary" />
            </div>
            <h3 className="font-display text-2xl font-bold text-foreground mb-4">
              Premium Access Required
            </h3>
            <p className="text-muted-foreground mb-6">
              Create an account to access our exclusive card marketplace with guaranteed success rates.
            </p>
            <div className="space-y-2 text-sm text-muted-foreground">
              <p>• Instant delivery</p>
              <p>• 24/7 support via Telegram</p>
              <p>• Verified success rates</p>
            </div>
          </div>
        </div>
      </section>
    );
  }

  return (
    <section id="products" className="py-20">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="font-display text-4xl font-bold text-foreground mb-4">
            Premium Card Collection
          </h2>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Curated selection of high-quality cards with verified success rates
          </p>
        </div>

        <div className="flex justify-center mb-8">
          <div className="flex flex-wrap justify-center gap-1 bg-card rounded-lg p-1 border border-border">
            {['all', 'premium', 'standard', 'basic', 'giftcard', 'transfer'].map((filterOption) => (
              <Button
                key={filterOption}
                onClick={() => setFilter(filterOption as any)}
                variant={filter === filterOption ? 'default' : 'ghost'}
                className={filter === filterOption ? 'btn-gold' : 'text-muted-foreground hover:text-foreground'}
                size="sm"
              >
                {filterOption === 'giftcard' ? 'Gift Cards' : filterOption === 'transfer' ? 'Transfers' : filterOption.charAt(0).toUpperCase() + filterOption.slice(1)}
              </Button>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredProducts.map((product) => (
            <ProductCard key={product.id} product={product} />
          ))}
          {filteredGiftCards.map((giftCard) => (
            <GiftCard key={giftCard.id} product={giftCard} />
          ))}
          {filteredTransfers.map((transfer) => (
            <MoneyTransfer key={transfer.id} product={transfer} />
          ))}
        </div>

        {filteredProducts.length === 0 && filteredGiftCards.length === 0 && filteredTransfers.length === 0 && (
          <div className="text-center py-12">
            <p className="text-muted-foreground">No products found for the selected filter.</p>
          </div>
        )}
      </div>
    </section>
  );
}